### ISSUE TITLE
layers.Process is missing `args` field

### ISSUE THREAD

**Issue by briandealwis** [buildpack/libbuildpack#11]
The [`launch.toml` format](https://github.com/buildpack/spec/blob/master/buildpack.md#launchtoml-toml) includes an `args` field.
```toml
[[processes]]
type = "<process type>"
command = "<command>"
args = ["<arguments>"]
direct = false

[[slices]]
paths = ["<app sub-path glob>"]
```

The corresponding Go struct, `layers.Process`, is missing this field.
https://github.com/buildpack/libbuildpack/blob/e8d3e9f32d486c6d75e619a3ae18a83f53c7b701/layers/process.go#L22-L32
